((haskell-mode . ((haskell-indentation-layout-offset . 4)
                  (haskell-indentation-starter-offset . 4)
                  (haskell-indentation-left-offset . 4)
                  (haskell-indentation-ifte-offset . 4)
                  (haskell-indentation-where-pre-offset . 4)
                  (haskell-indentation-where-post-offset . 4))))
