#!/bin/bash
set -ex
cabal --version
if [[ "${GHCVER}" > "7.2.2" ]] ; then
  /opt/cabal/${CABALVER}/bin/cabal install --only-dependencies --enable-tests
else
  /opt/cabal/${CABALVER}/bin/cabal install --only-dependencies
  echo "Skipping test dependency install on ${GHCVER}"
fi
