#!/bin/bash
set -ex
if [[ "${GHCVER}" > "7.2.2" ]] ; then
  cabal install --only-dependencies --enable-tests
else
  cabal install --only-dependencies
  echo "Skipping test dependency install on ${GHCVER}"
fi
