#!/bin/bash
set -ex
cabal --version

GHC_IS_OLD=$(python -c "from distutils.version import StrictVersion as SV; print '$GHCVER' != 'head' and SV('$GHCVER') < SV('7.2.3')")

if [[ "False" == "$GHC_IS_OLD" ]] ; then
  /opt/cabal/${CABALVER}/bin/cabal install --only-dependencies --enable-tests
else
  /opt/cabal/${CABALVER}/bin/cabal install --only-dependencies
  echo "Skipping test dependency install on ${GHCVER}"
fi
